require("zmum.colorscheme")
require("zmum.cmp")
require("zmum.plugins")
require("zmum.remap")
require("zmum.treesitter")
require("zmum.vim_settings")
-- require("zmum.status_line")
require("zmum.lsp.init")
require("zmum.autopairs")
require("zmum.gitsigns")
require("zmum.nvimtree")
require("zmum.bufferline")
require("zmum.null_ls")
require("zmum.telescope")
require("zmum.mason_null_ls")
require("zmum.copilot")
