require("zmum.colors")
require("zmum.completion")
require("zmum.plugins")
require("zmum.remap")
require("zmum.treesitter")
require("zmum.vim_settings")
require("zmum.ale_config")
-- require("zmum.status_line")
require("zmum.lsp.init")
require("zmum.autopairs")
require("zmum.gitsigns")
require("zmum.nvimtree")
require("zmum.bufferline")
require("zmum.null_ls")
require("zmum.telescope")
